before_script:
  - ruby -v
  - which ruby
  - gem install bundler --no-document
  - bundle install --jobs $(nproc) --path vendor/bundle

test:Ruby 2.4:
  image: ruby:2.4
  cache:
    paths:
      - .bundle
      - vendor/bundle
  script:
    - bundle exec rubocop
  tags:
    - ruby
  except:
    - tags

release:Ruby 2.4:
  image: ruby:2.4
  cache:
    paths:
      - .bundle
      - vendor/bundle
  script:
    - bundle exec rubocop
    - gem install dpl --no-document
    - dpl --provider=rubygems --api-key=$RUBYGEMS_API_KEY
  artifacts:
    name: "chef-rundeck2-$CI_BUILD_REF_NAME"
    paths:
      - ./*.gem
  tags:
    - ruby
  only:
    - tags
