Style/ModuleFunction:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/FileName:
  Enabled: false

Style/EmptyLineAfterMagicComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

AllCops:
  Include:
    - lib/
